import PDFDocument from 'pdfkit';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { Analysis } from './analyzer.js';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function generateHTML(title: string, analysis: Analysis, createdAt: string): string {
  const section = (heading: string, items: string[] | { label: string; value: string }[]) => {
    if (Array.isArray(items) && items.length > 0 && typeof items[0] === 'string') {
      return `
        <section class="section">
          <h2>${heading}</h2>
          <ul>${(items as string[]).map((i) => `<li>${escapeHtml(i)}</li>`).join('')}</ul>
        </section>`;
    }
    return `
      <section class="section">
        <h2>${heading}</h2>
        <div class="metrics">
          ${(items as { label: string; value: string }[])
            .map(
              (k) => `
            <div class="metric-card">
              <div class="metric-label">${escapeHtml(k.label)}</div>
              <div class="metric-value">${escapeHtml(k.value)}</div>
            </div>`
            )
            .join('')}
        </div>
      </section>`;
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} — Business Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; padding: 2rem; }
    .container { max-width: 900px; margin: 0 auto; background: white; border-radius: 16px; padding: 3rem; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
    h1 { font-size: 2rem; color: #4f46e5; margin-bottom: 0.5rem; }
    .meta { color: #64748b; margin-bottom: 2rem; font-size: 0.9rem; }
    .section { margin-bottom: 2rem; }
    h2 { font-size: 1.25rem; color: #334155; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; margin-bottom: 1rem; }
    p { margin-bottom: 1rem; }
    ul { padding-left: 1.5rem; }
    li { margin-bottom: 0.5rem; }
    .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; }
    .metric-card { background: #f1f5f9; border-radius: 12px; padding: 1.25rem; text-align: center; }
    .metric-label { font-size: 0.85rem; color: #64748b; margin-bottom: 0.25rem; }
    .metric-value { font-size: 1.5rem; font-weight: 700; color: #4f46e5; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.8rem; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">Generated on ${escapeHtml(createdAt)} · AI Report Generator</div>

    <section class="section">
      <h2>Executive Summary</h2>
      <p>${escapeHtml(analysis.executiveSummary)}</p>
    </section>

    ${section('Key Numbers', analysis.keyNumbers)}

    ${section('Business Insights', analysis.businessInsights)}
    ${section('Growth Opportunities', analysis.growthOpportunities)}
    ${section('Potential Risks', analysis.potentialRisks)}
    ${section('Recommendations', analysis.recommendations)}

    <div class="footer">Confidential Business Report — Generated by AI Report Generator</div>
  </div>
</body>
</html>`;
}

export async function generatePDF(title: string, analysis: Analysis, createdAt: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(24).fillColor('#4f46e5').text(title, { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#64748b').text(`Generated on ${createdAt} · AI Report Generator`);
    doc.moveDown(1.5);

    const addSection = (heading: string) => {
      doc.moveDown(0.8);
      doc.fontSize(14).fillColor('#334155').text(heading);
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
      doc.moveDown(0.5);
    };

    addSection('Executive Summary');
    doc.fontSize(11).fillColor('#1e293b').text(analysis.executiveSummary, { align: 'justify' });

    addSection('Key Numbers');
    for (const kn of analysis.keyNumbers) {
      doc.fontSize(11).fillColor('#64748b').text(kn.label);
      doc.fontSize(16).fillColor('#4f46e5').text(kn.value);
      doc.moveDown(0.4);
    }

    const addListSection = (heading: string, items: string[]) => {
      addSection(heading);
      for (const item of items) {
        doc.fontSize(11).fillColor('#1e293b').text(`•  ${item}`, { indent: 10 });
        doc.moveDown(0.2);
      }
    };

    addListSection('Business Insights', analysis.businessInsights);
    addListSection('Growth Opportunities', analysis.growthOpportunities);
    addListSection('Potential Risks', analysis.potentialRisks);
    addListSection('Recommendations', analysis.recommendations);

    doc.end();
  });
}

export async function generateDOCX(title: string, analysis: Analysis, createdAt: string): Promise<Buffer> {
  const bulletItems = (items: string[]) =>
    items.map(
      (item) =>
        new Paragraph({
          text: item,
          bullet: { level: 0 },
          spacing: { after: 120 },
        })
    );

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            children: [new TextRun({ text: title, bold: true, size: 48, color: '4F46E5' })],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `Generated on ${createdAt} · AI Report Generator`, color: '64748B', size: 20 })],
            spacing: { after: 400 },
          }),
          new Paragraph({ text: 'Executive Summary', heading: HeadingLevel.HEADING_2, spacing: { after: 200 } }),
          new Paragraph({ text: analysis.executiveSummary, spacing: { after: 300 } }),
          new Paragraph({ text: 'Key Numbers', heading: HeadingLevel.HEADING_2, spacing: { after: 200 } }),
          ...analysis.keyNumbers.flatMap((kn) => [
            new Paragraph({
              children: [new TextRun({ text: kn.label, color: '64748B' })],
            }),
            new Paragraph({
              children: [new TextRun({ text: kn.value, bold: true, size: 32, color: '4F46E5' })],
              spacing: { after: 200 },
            }),
          ]),
          new Paragraph({ text: 'Business Insights', heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 200 } }),
          ...bulletItems(analysis.businessInsights),
          new Paragraph({ text: 'Growth Opportunities', heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 200 } }),
          ...bulletItems(analysis.growthOpportunities),
          new Paragraph({ text: 'Potential Risks', heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 200 } }),
          ...bulletItems(analysis.potentialRisks),
          new Paragraph({ text: 'Recommendations', heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 200 } }),
          ...bulletItems(analysis.recommendations),
          new Paragraph({
            children: [new TextRun({ text: 'Confidential Business Report — AI Report Generator', italics: true, color: '94A3B8', size: 18 })],
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 },
          }),
        ],
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
